# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-24 03:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasedelicencia', models.CharField(max_length=1)),
                ('fecha_obtencion', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Conductor',
                'verbose_name_plural': 'Conductores',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=30, null=True)),
                ('marca', models.CharField(max_length=30, null=True)),
                ('modelo', models.CharField(max_length=30, null=True)),
                ('maleta', models.BooleanField(default=True)),
                ('color', models.CharField(max_length=30, null=True)),
                ('Numeroasientos', models.IntegerField(default=0)),
                ('consumo', models.IntegerField(default=10)),
                ('foto', models.ImageField(null=True, upload_to='autos')),
            ],
        ),
        migrations.AddField(
            model_name='conductor',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conductor.Vehiculo'),
        ),
    ]
