# Generated by Django 2.2 on 2019-05-02 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0003_remove_viaje_chofer'),
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductor',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='viaje.Viaje'),
        ),
        migrations.AlterField(
            model_name='conductor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
    ]
