# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 10:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0002_auto_20190503_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_conductor', to=settings.AUTH_USER_MODEL),
        ),
    ]
