# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interes_personal',
            old_name='Interes',
            new_name='interes',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Dirección',
            new_name='dirección',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Fumador',
            new_name='fumador',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Numero_teléfono',
            new_name='numero_teléfono',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Profesión',
            new_name='profesión',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Rut',
            new_name='rut',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='Valoración',
            new_name='valoración',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='Nombre',
        ),
    ]
