# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_auto_20190614_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='dirección',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='numero_teléfono',
            new_name='numero_telefono',
        ),
        migrations.RenameField(
            model_name='perfil',
            old_name='profesión',
            new_name='profesion',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='valoración',
        ),
        migrations.AddField(
            model_name='perfil',
            name='valoracion',
            field=models.FloatField(default=5.0),
        ),
    ]
