# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_auto_20190613_1924'),
        ('usuario', '0004_auto_20190617_0238'),
        ('usuario', '0004_auto_20190616_0141'),
    ]

    operations = [
    ]
