# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-17 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_merge_20190617_1609'),
        ('usuario', '0005_merge_20190617_1519'),
    ]

    operations = [
    ]
