# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 01:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0007_auto_20190617_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='mensajes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='usuario',
            name='viajes_en_curso',
            field=models.IntegerField(default=0),
        ),
    ]
