# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0008_auto_20190707_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='mensajes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='viajes_en_curso',
        ),
        migrations.AddField(
            model_name='perfil',
            name='mensajes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='perfil',
            name='viajes_en_curso',
            field=models.IntegerField(default=0),
        ),
    ]
