# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 05:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0009_perfil_email'),
        ('usuario', '0009_auto_20190707_0124'),
    ]

    operations = [
    ]
