# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 08:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_merge_20190708_0521'),
        ('usuario', '0010_merge_20190708_0506'),
    ]

    operations = [
    ]
