# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0012_merge_20190708_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='mensajes',
            field=models.CharField(default='', max_length=50),
        ),
    ]
