# Generated by Django 2.0 on 2019-07-10 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20190709_2218'),
        ('usuario', '0013_auto_20190709_1605'),
    ]

    operations = [
    ]
