# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0013_auto_20190709_1723'),
        ('usuario', '0013_auto_20190709_2218'),
        ('usuario', '0013_auto_20190709_1605'),
    ]

    operations = [
    ]
