# Generated by Django 2.0 on 2019-07-10 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_merge_20190709_2230'),
        ('usuario', '0013_auto_20190709_1723'),
    ]

    operations = [
    ]
