# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_merge_20190710_0422'),
        ('usuario', '0013_auto_20190709_1723'),
    ]

    operations = [
    ]
