# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 04:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0014_merge_20190710_0334'),
        ('usuario', '0015_merge_20190710_0430'),
    ]

    operations = [
    ]
