# Generated by Django 2.0 on 2019-07-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0015_merge_20190709_2332'),
        ('usuario', '0015_merge_20190710_0430'),
    ]

    operations = [
    ]
