# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 05:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_merge_20190710_0052'),
        ('usuario', '0016_merge_20190710_0435'),
    ]

    operations = [
    ]
