# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_auto_20190710_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(default='static/fotos_perfil/user-icon.jpg', upload_to='static/fotos_perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='mensajes',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
