# Generated by Django 2.0 on 2019-07-10 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0016_merge_20190710_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('anonimo', models.BooleanField(default=False)),
                ('usuarioEvaluado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosEvaluado', to=settings.AUTH_USER_MODEL)),
                ('usuarioEvaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosEvaluador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
    ]
