# Generated by Django 2.0 on 2019-07-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_merge_20190710_0550'),
        ('usuario', '0017_valoracion'),
    ]

    operations = [
    ]
