# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_merge_20190710_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('comentario', models.TextField()),
                ('anonimo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Valoracion',
                'verbose_name_plural': 'Valoraciones',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='usuarioEvaluado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosEvaluado', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valoracion',
            name='usuarioEvaluador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuariosEvaluador', to=settings.AUTH_USER_MODEL),
        ),
    ]
