# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_valoracion'),
        ('usuario', '0018_auto_20190710_1609'),
    ]

    operations = [
    ]
