# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-10 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0017_auto_20190710_0600'),
        ('usuario', '0019_merge_20190710_1647'),
        ('usuario', '0018_merge_20190710_1258'),
    ]

    operations = [
    ]
