# Generated by Django 2.0 on 2019-07-10 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0019_merge_20190710_1647'),
        ('usuario', '0018_merge_20190710_1258'),
    ]

    operations = [
    ]
