# Generated by Django 2.2 on 2019-05-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=40)),
                ('destino', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
