# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='Estado',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Mascotas',
            new_name='mascotas',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Max_personas_atras',
            new_name='max_personas_atras',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Porta_maleta',
            new_name='porta_maleta',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='Silla_niños',
            new_name='silla_niños',
        ),
        migrations.RenameField(
            model_name='viaje',
            old_name='TarifaPreferencias',
            new_name='tarifaPreferencias',
        ),
    ]
