# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0002_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramo',
            name='distancia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
