# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0006_remove_conductor_viajes'),
        ('viaje', '0003_viaje_conductor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='conductor',
        ),
        migrations.AddField(
            model_name='viaje',
            name='conductor',
            field=models.ManyToManyField(blank=True, null=True, related_name='_viajes', to='conductor.Conductor'),
        ),
    ]
