# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-03 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conductor', '0006_remove_conductor_viajes'),
        ('viaje', '0004_auto_20190503_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='conductor',
        ),
        migrations.AddField(
            model_name='viaje',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_viajes', to='conductor.Conductor'),
        ),
    ]
