# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-26 20:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0004_auto_20190526_0733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramo',
            name='distancia',
        ),
    ]
