# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0006_tramo_distancia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tramos',
            field=models.ManyToManyField(related_name='Reserva', to='viaje.Tramo'),
        ),
        migrations.AlterField(
            model_name='tramo',
            name='hora_llegada',
            field=models.TimeField(default='15:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='tramo',
            name='hora_salida',
            field=models.TimeField(default='15:00', max_length=30),
        ),
    ]
