# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 05:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0007_auto_20190527_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='hora_llegada',
            field=models.CharField(default='15:00', max_length=30, validators=[django.core.validators.MinValueValidator('00:00'), django.core.validators.MaxValueValidator('23:59')]),
        ),
    ]
