# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-07 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0007_auto_20190606_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='tramos',
            field=models.ManyToManyField(related_name='Tramos', to='viaje.Tramo'),
        ),
    ]
