# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0008_auto_20190527_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='hora_llegada',
            field=models.CharField(default='15:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='tramo',
            name='hora_salida',
            field=models.CharField(default='15:00', max_length=30),
        ),
    ]
