# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-10 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0008_auto_20190607_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramo',
            name='viaje',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
