# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-11 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0009_auto_20190527_0604'),
        ('viaje', '0009_tramo_viaje'),
    ]

    operations = [
    ]
