# Generated by Django 2.0 on 2019-06-14 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0011_auto_20190612_1523'),
        ('viaje', '0011_auto_20190612_1928'),
    ]

    operations = [
    ]
