# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0012_merge_20190614_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramo',
            name='fecha',
            field=models.DateTimeField(default='21/10/18', max_length=30),
        ),
    ]
