# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0015_auto_20190615_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='fecha',
            field=models.DateField(),
        ),
    ]
