# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0016_auto_20190615_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='tramos',
            field=models.ManyToManyField(related_name='reservas', to='viaje.Tramo'),
        ),
    ]
