# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-15 22:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0017_auto_20190615_2250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viaje',
            old_name='max_personas_atras',
            new_name='plazas_disponibles',
        ),
    ]
