# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-06 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0018_auto_20190615_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='parada_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ParadaActual', to='viaje.Parada'),
        ),
    ]
