# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-07 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0019_viaje_parada_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='parada_actual',
            field=models.IntegerField(default=1),
        ),
    ]
