# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0020_auto_20190707_2006'),
        ('viaje', '0019_viaje_tramo_actual'),
    ]

    operations = [
    ]
