# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-08 05:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0021_merge_20190708_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='tramo_actual',
        ),
    ]
