# Generated by Django 2.2 on 2019-05-02 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=40)),
                ('destino', models.CharField(max_length=40)),
                ('fecha', models.DateTimeField()),
                ('chofer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conductor.Conductor')),
            ],
        ),
    ]
