# Generated by Django 2.2 on 2019-05-02 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viaje', '0002_auto_20190502_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='chofer',
        ),
    ]
