# Generated by Django 2.2 on 2019-05-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=70)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('domicilio', models.TextField()),
                ('rut', models.IntegerField()),
            ],
        ),
    ]
